apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: centos
    image: alpine 
    command: ["sleep", "300"]
    envFrom: 
      - secretRef: 
          name: demo-secret

---

apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
data:
  USERNAME: YWRtaW450
  PASSWORD: cGFzc3dvcmQK
