# Single Pod : Single Container
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    tier: frontend
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    tier: frontend
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 80