apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: nginx:1.23.1-perl
        ports:
        - containerPort: 80

--- 
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  selector:
    app: httpd
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 80

--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpd-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "httpd.roboshopdirect.com"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: httpd-service
            port:
              number: 80