apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-cm
data:
  REDIS_HOST: redis-dev.roboshopdirect.internal
  CATALOGUE_HOST: catalogue-service

--- 

apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-cm
data:
  MONGO_URL: "mongodb://admin1:roboshop1@roboshop-dev.cluster-ciqb6xvrbz0q.us-east-1.docdb.amazonaws.com:27017/catalogue?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"      

--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-cm
data:
  CART_HOST: cart-service 
  USER_HOST: user-service 
  AMQP_HOST: rabbitmq-dev.roboshopdirect.internal
  AMQP_USER: roboshop 
  AMQP_PASS: roboshop123

--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-cm
data:
  DB_HOST: mysql-dev.roboshopdirect.internal
  CART_ENDPOINT: cart-service 


--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-cm
data:
  REDIS_HOST: redis-dev.roboshopdirect.internal
  MONGO_URL: mongodb://admin1:roboshop1@roboshop-dev.cluster-ciqb6xvrbz0q.us-east-1.docdb.amazonaws.com:27017/users?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false

--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-cm
data:
  REDIS: resis 